### ISSUE TITLE
Failed to write configuration: wanIf

### ISSUE THREAD

**Issue by j0hnnie** [91yun/serverspeeder#1]
hi，内核已升级至2.63.23 504 3.3 （centos 6.6）
一路都顺利，就是到最后会报：
Failed to write configuration: wanIf
然后无法启动ss

**Comment by 91yun** [comment]
无法启动ss还是锐速？

**Comment by elsonwu** [comment]
根据这个page的配置http://blog.deartanker.com/post/3723.html

相同的error:

> ---
> 
> You are about to be asked to enter information that will be used by ServerSpeeder,
> there are several fields and you can leave them blank,
> 
> ## for all fields there will be a default value.
> 
> Enter your accelerated interface(s) [eth0]: 56:00:00:26:35:97  
> Enter your outbound bandwidth [1000000 kbps]: 
> Enter your inbound bandwidth [1000000 kbps]: 
> 
> Notice:After set shorttRtt-bypass value larger than 0,
> it will bypass(not accelerate) all first flow from same 24-bit
> network segment and the flows with RTT lower than the shortRtt-bypass value
> 
> Configure shortRtt-bypass [0 ms]: 
> Auto load ServerSpeeder on linux start-up? [n]:
> Run ServerSpeeder now? [y]:y
> (license 603345D09BAA6C40043d3695)
> Failed to write configuration: wanIf(56:00:00:26:35:97)
> [Running Status]
> ServerSpeeder is NOT running!
> version              3.10.61.0
> 
> [License Information]
> License              603345D09BAA6C40 (valid on current device)
> MaxSession           unlimited
> MaxTcpAccSession     unlimited
> MaxBandwidth(kbps)   unlimited
> ExpireDate           2034-12-31

**Comment by 91yun** [comment]
Enter your accelerated interface(s) [eth0]: 56:00:00:26:35:97
错误。应直接回车，不要输入mac。使用最新的脚本已经不会让大家输入这个东西了。
