### ISSUE TITLE
锐速破解版，有时候会假死，无加速

### ISSUE THREAD

**Issue by Randy000** [91yun/serverspeeder#10]
![image](https://cloud.githubusercontent.com/assets/10096850/14941684/12c4c56c-0fd7-11e6-91eb-2c7aac581f8d.png)
今日我用上破解版的锐速。竟然发觉会假死。正如图里看到的“连接信息”全为0。锐速虽然在运行，但是，却毫无加速效果。
然后，我重启了锐速的服务，问题解决。不知下次是什么时候假死呢。。
![image](https://cloud.githubusercontent.com/assets/10096850/14941687/3152bd2c-0fd7-11e6-8873-b864a6b52cac.png)
感觉还是正版的稳定。现在“connection information”不再为0.

用的是手动安装版，并非自动匹配版。

**Comment by Randy000** [comment]
系统：Ubuntu 14.04.4 LTS (GNU/Linux 3.18.5-x86_64-linode52 x86_64)

对应的锐速内核版本：Ubuntu_14.10_3.18.5-x86_64-linode52
安装的锐速版本：3.10.61.0
用免费版锐速，也是这个锐速版本。从未出现过假死状况。

**Comment by 91yun** [comment]
有用Ubuntu的用户反馈过,不过我也不清楚什么原因引起的...因为我一直用centos,所以Ubuntu很多问题我也不太了解..

**Comment by Randy000** [comment]
感谢你的回复。锐速重启后似乎未再发现假死状态，有log的时候，我会再回复下。:)。

**Comment by Randy000** [comment]
系统日志
May  3 07:25:38 kernel: appex: set wanIf $+ppp0
May  3 07:25:38 kernel: appex: intf: $+ppp0 not found.
May  3 07:25:41 kernel: appex:  is down
May  3 07:25:41 kernel: appex:  is down
May  3 07:25:42 kernel: appex: set wanIf $+ppp0
May  3 07:25:42 kernel: appex: intf: $+ppp0 not found.
May  3 07:46:41 kernel: appex:  is down
May  3 07:46:41 kernel: appex:  is down
May  3 07:46:41 kernel: appex:  is del

今天（5月3日）锐速又没加速效果了。查了下日志。似乎是网卡找不到。。 ppp0网卡，我的是eth0的。
 然后，我又得重启锐速服务
sudo /serverspeeder/bin/serverSpeeder.sh restart

May  4 01:19:55 kernel: appex: set wanIf eth0
May  4 01:19:55 kernel: appex: set wanIf eth0 in routed mode

**Comment by 91yun** [comment]
今天也有人反应网卡变成 $+ppp0的问题.我也不清楚原因..但关闭ppp加速似乎可以解决.配置文件设置accppp=0

**Comment by Randy000** [comment]
我才发觉我那个时间段登录了VPN，而锐速就del掉，我比对了以前的配置，ACCPPP默认是被关闭的，这个功能是用来加速VPN的。。

## 我已经关闭了PPP加速，希望锐速可以稳定运作咯。感谢你的 深夜回复。:)

需要加速V-P-N
默认设置下锐速不加速V-P-N。
如需加速PPTP、L2TP V-P-N需要修改/serverspeeder/etc/config 将accppp="0"改为accppp="1"
并重启锐速:service serverSpeeder restart

如需加速OpenV-P-N等其他使用tun设备的V-P-N。
请先用ifconfig命令查看对应V-P-N设备的名称 多数情况下是tun0
需要修改/serverspeeder/etc/config 在accif="eth0"内加入tun0。最后应当看起来是accif="eth0 tun0"
并重启锐速:service serverSpeeder restart

http://bbs.tcp.hk/thread-27-1-1.html

**Comment by itwo123** [comment]
重启服务出现:
ln: failed to create symbolic link `/etc/ppp/ip-down.local': No such file or directory
问题: 是不是无关紧要

**Comment by 91yun** [comment]
是。不用理他。如果你没有安装pptpd等vpn的话
