### ISSUE TITLE
求centos7.2锐速破解版！！！

### ISSUE THREAD

**Issue by jiangjiangflies** [91yun/serverspeeder#11]

**Comment by 91yun** [comment]
是破解的,所以版本也不会再更新,所以不会有新版的破解锐速啦.不过7.2如果按照我的centos7的降内核方法,降了内核后也可以用7的锐速.

**Comment by jiangjiangflies** [comment]
降内核的方法麻烦给个链接吧

**Comment by jiangjiangflies** [comment]
按照你的方法，我centos7.2更换内核为 3.10.0-327.10.1.el7.x86_64，下载了centos7.1 最接近的锐速版本3.10.61.12。提示
engineId=0 cpuId=0 cpuMaskNum=1 packetPoolSizeKP=256 : Invalid parameters
..............................Loading ServerSpeeder failed: failed to load engine 0
[Running Status]
ServerSpeeder is NOT running!
version              3.10.61.0

**Comment by 91yun** [comment]
这是内核不匹配的症状.那就没办法了...安装低版本操作系统吧o(╯□╰)o
