### ISSUE TITLE
KVM速锐无法正常安装

### ISSUE THREAD

**Issue by devillaws** [91yun/serverspeeder#12]
![image](https://cloud.githubusercontent.com/assets/8604432/14950308/495f4780-1083-11e6-97e1-308b49db7510.png)

![image](https://cloud.githubusercontent.com/assets/8604432/14950361/98c0bc00-1083-11e6-985f-8c1b1a609a29.png)

本VPS租于sakura商，之前别的运营商两台KVM均可正常安装，其中需要填写一些配置信息，但本次不需要填写并直接结束，使用卸载命令提示找不到speeder，请问这是什么情况，另外已用命令保证本VPS为KVM

**Comment by 91yun** [comment]
因为没有安装吧.不知道为什么保存的文件是乱码...所以那个命令其实都没有执行.

**Comment by devillaws** [comment]
![image](https://cloud.githubusercontent.com/assets/8604432/14976494/ba7ce330-113e-11e6-8891-5d56ff0057e5.png)
这边发现系统内核不在破解版支持范围内，请问是这原因吗，如果是，我有什么可行方法，可降级么^ ^

**Comment by 91yun** [comment]
http://www.91yun.org/archives/795 我只熟悉centos,有centos的更换内核方法
