### ISSUE TITLE
为何ethtool这个文件与别的安装包版本不一样？

### ISSUE THREAD

**Issue by tx9191** [91yun/serverspeeder#14]
与从https://iforday.com/78.html以及https://crystal.fantasy.pe/build.html下载的文件对比，ethtool出现不一致，而以上两个来源的ethtool是一致的

**Comment by 91yun** [comment]
我不知道你的不一致是指什么。经我对比。两者的md5完全一样

**Comment by tx9191** [comment]
那么从你的网站下载的ethtool的md5是否可以贴出来？

**Comment by 91yun** [comment]
既然你都有3个来源下载的文件了.为啥不自己比对下呢

**Comment by tx9191** [comment]
你的服务器设在中国，某些中间人也可能把文件替换掉，对不对？

**Comment by tx9191** [comment]
抱歉，重新下载比较了一次，发现与其他不一致的应该是 https://iforday.com/78.html 下的Debian_7_3.2.0-4-686-pae里的ethtool，之前弄混乱了。
