### ISSUE TITLE
新的启动问题，在CentOS6 64bit

### ISSUE THREAD

**Issue by Aloento** [91yun/serverspeeder#16]
长 度 ： 9650 (9.4K) [text/plain]
正 在 保 存 至 : “serverspeeder-all.sh”

100%[===================================>] 9,650       --.-K/s   in 0s

缺 少 “Last-modified”文 件 头 -- 关 闭 时 间 戳 标 记 。
2016-05-26 08:50:17 (29.1 MB/s) - 已 保 存  “serverspeeder-all.sh” [9650/9650])

rpmdb: Thread/process 2558/140348373333760 failed: Thread died in Berkeley DB
 library
error: db3 error(-30974) from dbenv->failchk: DB_RUNRECOVERY: Fatal error, ru
n database recovery
error: cannot open Packages index using db3 -  (-30974)
error: cannot open Packages database in /var/lib/rpm
CRITICAL:yum.main:

Error: rpmdb open failed
serverspeeder-all.sh: line 18: apt-get: command not found
serverspeeder-all.sh: line 18: apt-get: command not found
lsb_release没 安 装 成 功 ， 程 序 暂 停

**Comment by Aloento** [comment]
为什么在CentOS下会调用到apt-get？

**Comment by 91yun** [comment]
已修正
