### ISSUE TITLE
`libcrypto.so.10' not found

### ISSUE THREAD

**Issue by ascfin** [91yun/serverspeeder#17]
ServerSpeeder is NOT running!
version              3.10.61.0

[License Information]
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])

**Comment by xiaobailong24** [comment]
Have sovled? The same issue I got, Thank you!

**Comment by 91yun** [comment]
此问题google解决吧。我不用Ubuntu，帮不了你们。

**Comment by pwparker** [comment]
This similar may help to read:   https://github.com/symless/synergy/issues/5439
