### ISSUE TITLE
libssl.so.10 & libcrypto.so.10 not found

### ISSUE THREAD

**Issue by xiaobailong24** [91yun/serverspeeder#19]
**> DigitalOcean VPS(KVM): Ubuntu 14.04 x64 vmlinuz-3.13.0-74-generic** 

**# 1.** 

Installation

 done!

/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
Load ServerSpeeder failed!
[Running Status]
ServerSpeeder is NOT running!
version              3.10.61.0

[License Information]
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

**# 2.** 
I try :
cd /lib/x86_64-linux-gnu
sudo ln -s libssl.so.1.0.0 libssl.so.10
sudo ln -s libcrypto.so.1.0.0 libcrypto.so.10
then 
cd /serverspeeder/bin
./serverSpeeder.sh start
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])
Load ServerSpeeder failed!

./serverSpeeder.sh status
[Running Status]
ServerSpeeder is NOT running!
version              3.10.61.0

[License Information]
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])

help me?

**Comment by FateTestarossa** [comment]
build openssl1.0.0 with shared option, default openssl release in most system is too new for serverspeeder.

**Comment by xiaobailong24** [comment]
(1)check openssl version
~# openssl version
OpenSSL 1.0.1f 6 Jan 2014
(2)uninstall openssl
~# apt-get purge openssl
(3)download openssl 1.0.0
~# wget ftp://ftp.openssl.org/source/openssl-1.0.0t.tar.gz
(4)make && install
~# tar -zxf openssl-1.0.0t.tar.gz
~# cd openssl-1.0.0t/
~# ./config  --prefix=/usr/local --openssldir=/usr/local/ssl
~# make && make install
~# ./config shared --prefix=/usr/local --openssldir=/usr/local/ssl
~# make clean
~# make && make install
(5)check again
~# openssl version
OpenSSL 1.0.0t 3 Dec 2015
(6)install serverspeeder
~# bash 91yunserverspeeder.sh

# (7)error 

# 开始下载授权文件。。。。

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

# 100   152    0   152    0     0    748      0 --:--:-- --:--:-- --:--:--   748

# 开始修改配置文件。。。。

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16    0    16    0     0     94      0 --:--:-- --:--:-- --:--:--    94

# 序列号：037C778286150F89

# 开始下载bin运行文件。。。。

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  519k  100  519k    0     0   940k      0 --:--:-- --:--:-- --:--:--  939k
cp: cannot remove ‘/serverspeeder/etc/apx-20341231.lic’: Operation not permitted
Installation done!

/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])
Load ServerSpeeder failed!
[Running Status]
ServerSpeeder is NOT running!
version              3.10.61.0

[License Information]
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])
root@xiaobailong24:~/SS/ruisu# cd /serverspeeder/etc/
root@xiaobailong24:/serverspeeder/etc# ls
apx-20341231.lic  config

**Comment by xiaobailong24** [comment]
Now libcrypto.so.10 not found
[License Information]
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])

**Comment by FateTestarossa** [comment]
you should build openssl 1.0.0 and then rename/link library to old library name: 'libssl.so.10' and 'libcrypto.so.10'.

**Comment by FateTestarossa** [comment]
It's not necessary and not recommended to remove openssl with package manager.
build openssl with:
./config shared linux-x86_64
make
libraries you need are libssl.so.1.0.0 and libcrypto.so.1.0.0
copy and rename them to /usr/lib or maybe /usr/lib/x86_64-linux-gnu in ubuntu(Tested with openssl-1.0.0f on ubuntu server 14.04LTS)

**Comment by ruiruige** [comment]
@FateTestarossa FateTestarossa is right 
I did as he/she said ，and it is successfully  working now
But if it your uname -a says linux version is not in the list
there may be other problems

**Comment by ipcjs** [comment]
我通过换内核的方式解决的。内核和版本的匹配关系：

```
ubuntu14.04+64+3.13.0-48-generic+3.11.20.4：OK
ubuntu14.04+64+3.13.0-74-generic+3.11.20.4：提示`libcrypto.so.10′ not found
ubuntu14.04+64+3.13.0-43-generic+3.10.66.29：OK
```

**Comment by 91yun** [comment]
You can refer to https://www.similarweb.com/website/91yun.org
----- 原始邮件 -----
发件人：ruiruige <notifications@github.com>
收件人：91yun/serverspeeder <serverspeeder@noreply.github.com>
主题：Re: [91yun/serverspeeder] libssl.so.10 & libcrypto.so.10 not found (#19)
日期：2016年10月14日 16点42分

@FateTestarossa FateTestarossa is right 

I did as he/she said ，and it is successfully  working now

But if it your uname -a says linux version is not in the list

there may be other problems

&mdash;

**Comment by TamerHussien** [comment]
mongod --version
mongod: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by mongod)
mongod: /lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by mongod)
and when i check the  /lib/x86_64-linux-gnu/ folder these files already their 
can any one help me

**Comment by SunnnyGohil** [comment]
@TamerHussien i have same problem. if you get solution then please help me
