### ISSUE TITLE
运行的时候遇到了这样的错误

### ISSUE THREAD

**Issue by idy** [91yun/serverspeeder#2]
(license 48395539173954461358b763)
Incorrect license 483966F528F55446.
Load ServerSpeeder failed!

**Comment by idy** [comment]
在国外的主机安装不会出现这个错误，在国内的主机安装会报错 :)

**Comment by idy** [comment]
出问题的国内主机使用的是 eth1 网卡

**Comment by 91yun** [comment]
目前非eth0好像会有问题。你 ip link 看看是否有eth0的网卡。如果有eth0的网卡，使用eth0的网卡mac算序列号。具体使用方式是在`serverspeeder-all.sh mac地址` 把eth0的mac地址作为参数。

**Comment by idy** [comment]
哦 明白了 确实是该问题
感谢开源项目 :)
