### ISSUE TITLE
运行一段时间后，会自动失去加速效果

### ISSUE THREAD

**Issue by silentAllay** [91yun/serverspeeder#21]
问题：运行一段时间后，会自动失去加速效果。
执行serverspeeder.sh stats命令，显示全部为0；
执行serverspeeder.sh restart，加速效果恢复.
运行环境:centos 6.7

**Comment by 91yun** [comment]
由于对锐速本身的运行机制和代码不了解，所以碰到此类问题，只能通过加入定时重启的crontab来解决
