### ISSUE TITLE
你的网站是不是出问题了

### ISSUE THREAD

**Issue by OXERIS** [91yun/serverspeeder#23]
锐速装不了，提示文件无法下载
 http://www.91yun.org/serverspeeder91yun也打不开了

**Comment by 91yun** [comment]
被ddcc中

**Comment by keysona** [comment]
@91yun 
ddos？
今天下午开始就上不了。

**Comment by OXERIS** [comment]
![default](https://cloud.githubusercontent.com/assets/18722082/16103307/f36dd680-33a9-11e6-93ea-f522a4603f6e.PNG)
现在网站没有恢复，但是可以安装了，但是版本号又出问题了，之前我在CentOS 6.7安装的时候安装的时候锐速版本貌似是2.6.x，而且可以安装，不知道我记错没有，但之前没有出现因为内核版本不对而无法安装的问题
