### ISSUE TITLE
CentOS 7 with broken pipe error forshadowsocks.

### ISSUE THREAD

**Issue by 1a57danc3** [91yun/serverspeeder#27]
sys info: Linux localhost.localdomain 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

connect youtube.com occur this error.

2016-07-24 08:42:21 ERROR    [Errno 32] Broken pipe

uninstall this script can recovery.

**Comment by 91yun** [comment]
ss的问题到ss的github问
