### ISSUE TITLE
这几天是不是出问题了？找不到各种依赖包？

### ISSUE THREAD

**Issue by DearTanker** [91yun/serverspeeder#28]
```
[root@host ~]# bash serverspeeder-all.sh
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: repos.lax.quadranet.com
 * epel: mirror.chpc.utah.edu
 * extras: mirror.scalabledns.com
 * updates: repos.lax.quadranet.com
http://repos.lax.quadranet.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2607:fcd0:0:a::2: Network is unreachable"
Trying other mirror.
http://mirrors.evowise.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2a05:84c7::1005: Network is unreachable"
Trying other mirror.
http://repos.forethought.net/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://repo1.sea.innoscale.net/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2605:7900:1:2::2: Network is unreachable"
Trying other mirror.
http://mirrors.usinternet.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2605:8400:0:4::56: Network is unreachable"
Trying other mirror.
http://dallas.tx.mirror.xygenhosting.com/CentOS/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://pubmirrors.dal.corespace.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://bay.uchicago.edu/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://mirrors.cmich.edu/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://mirror.sesp.northwestern.edu/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
```

**Comment by 91yun** [comment]
你设置错什么了吧，好像都解析成ipv6的地址了。导致连不上。
----- 原始邮件 -----
发件人：DearTanker notifications@github.com
收件人：91yun/serverspeeder serverspeeder@noreply.github.com
主题：[91yun/serverspeeder]_这几天是不是出问题了？找不到各种依赖包？_(#28)
日期：2016年08月09日 23点35分

`[root@host ~]# bash serverspeeder-all.sh

Loaded plugins: fastestmirror

Setting up Install Process

Loading mirror speeds from cached hostfile

base: repos.lax.quadranet.com
epel: mirror.chpc.utah.edu
extras: mirror.scalabledns.com
updates: repos.lax.quadranet.com
http://repos.lax.quadranet.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2607:fcd0:0🅰️:2: Network is unreachable"
Trying other mirror.
http://mirrors.evowise.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2a05:84c7::1005: Network is unreachable"
Trying other mirror.
http://repos.forethought.net/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://repo1.sea.innoscale.net/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2605:7900:1:2::2: Network is unreachable"
Trying other mirror.
http://mirrors.usinternet.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2605:8400:0:4::56: Network is unreachable"
Trying other mirror.
http://dallas.tx.mirror.xygenhosting.com/CentOS/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://pubmirrors.dal.corespace.com/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://bay.uchicago.edu/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://mirrors.cmich.edu/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.
http://mirror.sesp.northwestern.edu/centos/6.8/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "couldn't connect to host"
Trying other mirror.`

&mdash;
