### ISSUE TITLE
有时候会导致ss服务死掉

### ISSUE THREAD

**Issue by u3shadow** [91yun/serverspeeder#30]
使用了破解版之后有时候会导致ss服务死掉，无法工作，重启后正常，求方案

**Comment by aircjm** [comment]
同求，现在只能使用crontab进行定时重启vps

**Comment by 91yun** [comment]
你要确定没有锐速的情况下，ss不会自己死掉。我自己的ss服务器暂时没碰到这些问题。

**Comment by aircjm** [comment]
我找到一篇博文,做了一个定时任务,定时重启服务搞定了,谢谢回复
