### ISSUE TITLE
不支持Ubuntu16.04

### ISSUE THREAD

**Issue by luchenqun** [91yun/serverspeeder#32]
# 

操作系统：Ubuntu 
发行版本：16.04 
内核版本：4.4.0-34-generic 
位数：x64 
# 锐速版本：3.10.61.0 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96179    0 96179    0     0   158k      0 --:--:-- --:--:-- --:--:--  158k

锐速暂不支持该内核，程序退出.自动安装判断比较严格，你可以到http://www.91yun.org/serverspeeder91yun手动下载安装文件尝试不同版本

**Comment by Eveink** [comment]
**把脚本这些部分删掉**
`#取操作系统的名称
Get_Dist_Name()
{
    if grep -Eqi "CentOS" /etc/issue || grep -Eq "CentOS" /etc/_-release; then
        DISTRO='CentOS'
        PM='yum'
    elif grep -Eqi "Debian" /etc/issue || grep -Eq "Debian" /etc/_-release; then
        DISTRO='Debian'
        PM='apt'
    elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then
        DISTRO='Ubuntu'
        PM='apt'
    else
        DISTRO='unknow'
    fi
    Get_OS_Bit
}

Get_OS_Bit()
{
    if [[ `getconf WORD_BIT` = '32' && `getconf LONG_BIT` = '64' ]] ; then
        ver3='x64'
    else
        ver3='x32'
    fi
}

Get_Dist_Name

#安装相应的软件
if [ "$DISTRO" == "CentOS" ];then
    yum install -y redhat-lsb curl net-tools
elif [ "$DISTRO" == "Debian" ];then
    apt-get update
    apt-get install -y lsb-release curl
elif [ "$DISTRO" == "Ubuntu" ];then
    apt-get update
    apt-get install -y lsb-release curl
else
    echo "一键脚本暂时只支持centos，ubuntu和debian的安装，其他系统请选择手动安装http://www.91yun.org/serverspeeder91yun"
    exit 1
fi

release=$DISTRO
#发行版本
if [ "$release" == "Debian" ]; then
    ver1str="lsb_release -rs | awk -F '.' '{ print \$1 }'"
else
    ver1str="lsb_release -rs | awk -F '.' '{ print \$1\".\"\$2 }'"
fi
ver1=$(eval $ver1str)
#ver11=`echo $ver1 | awk -F '.' '{ print $1 }'`

#内核版本
ver2=`uname -r`
#锐速版本
ver4=3.10.61.0`

**替换成**
`release=CentOS
ver1=6.5
ver2=4.4.0-x86_64-linode63
ver3=x64
ver4=3.10.61.0`

**Comment by invkrh** [comment]
系统： digital ocean / ubuntu 16.04

删除这段脚本还是不能成功运行：

显示 **Loading ServerSpeeder failed: failed to load engine 0**

```
======================================
开始下载授权文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152    0   152    0     0    910      0 --:--:-- --:--:-- --:--:--   915
======================================
开始修改配置文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16    0    16    0     0    111      0 --:--:-- --:--:-- --:--:--   111
序列号：CED4CE678ED8DAE1
======================================
开始下载bin运行文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  463k  100  463k    0     0  1046k      0 --:--:-- --:--:-- --:--:-- 1048k
Installation done!

(license CED4CE678ED8DAE146870b31)
engineId=0 cpuId=0 cpuMaskNum=1 packetPoolSizeKP=256 : Invalid module format
..............................Loading ServerSpeeder failed: failed to load engine 0
[Running Status]
ServerSpeeder is NOT running!
version              3.10.61.0

[License Information]
License              CED4CE678ED8DAE1 (valid on current device)
MaxSession           unlimited
MaxTcpAccSession     unlimited
MaxBandwidth(kbps)   unlimited
ExpireDate           2034-12-31
```
