### ISSUE TITLE
据说锐速有后门？

### ISSUE THREAD

**Issue by ghost** [91yun/serverspeeder#34]
网上很多人说锐速有后门？突然有点怕会不会被抓包发送给某朝？请博主开颗定心丸

**Comment by YumeMichi** [comment]
你可以自己在服务器上抓下包看看就知道数据有没有被发到奇♂怪的地方去

**Comment by 91yun** [comment]
锐速本身带不带后门不清楚，毕竟那是二进制文件。破解只破解了授权文件。
