### ISSUE TITLE
锐速破解版 加速vpn就失效

### ISSUE THREAD

**Issue by qinef** [91yun/serverspeeder#36]
内容已经在此贴有过讨论，不过没结果就关了。https://github.com/91yun/serverspeeder/issues/10

我装的是l2tp vpn，centos6.5 版 使用命令“vi /serverspeeder/etc/config ",将accppp="0"改为accppp="1"后，测试vpn加速明显，但是此时再使用/serverspeeder/bin/serverSpeeder.sh status 命令无法，锐速虽然在支行，实际上已经无加速效果了。现在唯有将accppp="0"改回来，请问有没有两全的办法，既能加速ss，又能加速vpn的呢

TotalFlow            0
NumOfTcpFlows      0
TotalAccTcpFlow     0
TotalActiveTcpFlow   0

**Comment by 91yun** [comment]
应该没有
