### ISSUE TITLE
支持的系统取消支持了

### ISSUE THREAD

**Issue by ghost** [91yun/serverspeeder#38]
操作系统：Debian
发行版本：8
内核版本：3.16.0-4-amd64
位数：x64
# 锐速版本：3.10.61.0

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95846    0 95846    0     0   129k      0 --:--:-- --:--:-- --:--:--  129k

锐速暂不支持该内核，程序退出.自动安装判断比较严格，你可以到http://www.91yun.org/serverspeeder91yun手动下载安装文件尝试不同版本

**Comment by smartpippin** [comment]
我用的CENT OS7也有同样的问题，之前都可以安装，现在全部报错。。。

**Comment by DearTanker** [comment]
CentOS 6.8 最新的642内核也是一样问题啊。。。10月初装的好好的，上周开始又不能装了@91yun

**Comment by VisoTC** [comment]
centos7最高只支持到7.1
centos6最高支持6.7
支持的版本
https://www.91yun.org/wp-content/plugins/91yun-serverspeeder/systemlist.html

> CentOS    6.7 2.6.32-042stab112.15    64-bits 3.11.20.4
>  CentOS 7   3.18.1-x86-linode68 32-bits 3.10.61.0
>  CentOS 7   3.18.1-x86_64-linode50  64-bits 3.10.61.0
>  CentOS 7   3.18.5-x86-linode70 32-bits 3.10.61.0
>  CentOS 7   3.18.5-x86_64-linode52  64-bits 3.10.61.0
>  CentOS 7   4.0.2-x86_64-linode56   64-bits 3.10.61.0
>  CentOS 7   4.1.0-x86_64-linode59   64-bits 3.10.66.25
>  CentOS 7   4.1.5-x86_64-linode60   64-bits 3.10.61.0
>  CentOS 7   4.1.5-x86_64-linode61   64-bits 3.10.61.0
>  CentOS 7.0 3.10.0-123.x86_64   64-bits 3.10.66.29
>  CentOS 7.1 3.10.0-229.1.2.el7.x86_64   64-bits 3.11.20.4

**Comment by DearTanker** [comment]
不是的，你搞错了，8月7号起已经支持最新的642内核，你可以看博主的文章，而且我月初才装过，都可以的，评论也有人讲到@szlytlyt

**Comment by hmmabc** [comment]
难道是迫于压力删除了？

**Comment by ghost** [comment]
@DearTanker 现在的确不行了，从10月15号下午开始很多内核都显示不匹配了。
