### ISSUE TITLE
锐速 运行一段时间后报错

### ISSUE THREAD

**Issue by sifksky** [91yun/serverspeeder#39]
ubuntu 14.04 的系统。 锐速运行一段时间后就自动退出，报如下错误。

/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: /lib/x86_64-linux-gnu/libcrypto.so.10: no version information available (required by /serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic])
(license 1A0767375B1F2614200f7042)
connect_to_server: connect to check server failed!
Regular check license connected to server failed!

**Comment by 91yun** [comment]
用最新的安装包吧。
