### ISSUE TITLE
Incorrect license key.

### ISSUE THREAD

**Issue by LeXwDeX** [91yun/serverspeeder#4]
一键安装完毕之后 提示 Incorrect license key. 

之前内核不对，安装了就提示破解失败，然后换了内核。
卸载再安装也一样，是不是哪里被藏文件了，没删干净。

**Comment by LeXwDeX** [comment]
网卡非eth0

**Comment by 91yun** [comment]
非eth0网卡目前有问题.请修改网卡名称

**Comment by LeXwDeX** [comment]
centos 可以通过 
#vi /etc/udev/rules.d/70-persistent-net.rules

#mv /etc/sysconfig/network-scripts/ifcfg-eth1  /etc/sysconfig/network-scripts/ifcfg-eth0

vi /etc/sysconfig/network-scripts/ifcfg-eth0
修改
