### ISSUE TITLE
一直提示证书过期有无解决办法？

### ISSUE THREAD

**Issue by RoyLaw** [91yun/serverspeeder#43]
Dec  4 22:53:35 hkg acce-3.10.61.0-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]: License expired
Dec  4 22:53:35 hkg acce-3.10.61.0-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]: License expired
Dec  4 22:54:37 hkg acce-3.10.61.0-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]: License expired
Dec  4 22:54:37 hkg acce-3.10.61.0-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]: License expired
Dec  4 22:55:39 hkg acce-3.10.61.0-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]: License expired
Dec  4 22:55:39 hkg acce-3.10.61.0-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]: License expired

我已经将dl.xx.com转到本地的一个http服务来应答验证的请求，但是仍旧会收到证书过期的提示，感觉锐速的功能已经失效了。

**Comment by iMarcs** [comment]
失效了。

**Comment by 91yun** [comment]
不知道你用的什么方法。

**Comment by pyoy** [comment]
我也遇到这个错，不知道怎么办
[root@localhost ~]# service serverSpeeder status
[Running Status]
ServerSpeeder is running!
version              3.10.66.29

[License Information]
License              9AE12DCF9D45A6EE (valid on current device)
MaxSession           unlimited
MaxTcpAccSession     unlimited
MaxBandwidth(kbps)   unlimited
ExpireDate           2034-12-31

[Connection Information]
TotalFlow            29101
NumOfTcpFlows        29101
TotalAccTcpFlow      25455
TotalActiveTcpFlow   7051

[Running Configuration]
accif                eth1 tun0      
acc                  0
advacc               1
advinacc             1
wankbps              10000000
waninkbps            10000000
csvmode              0
subnetAcc            0
maxmode              1
pcapEnable           0
[root@localhost ~]# 
Message from syslogd@localhost at Sep 13 15:02:24 ...
 nnect_to_server: get host failed

Message from syslogd@localhost at Sep 13 15:02:24 ...
 gular check license connected to server failed!

Message from syslogd@localhost at Sep 13 15:03:24 ...
 nnect_to_server: get host failed

Message from syslogd@localhost at Sep 13 15:03:24 ...
 gular check license connected to server failed!
^C
