### ISSUE TITLE
安装后发现流量异常，疑似入侵。

### ISSUE THREAD

**Issue by wilhantian** [91yun/serverspeeder#48]
RT

**Comment by 91yun** [comment]
别疑似，拿证据。自己学好linux相应的安全知识，完全不知道发帖的意义？我可以说疑似你脑子不正常不。

**Comment by wilhantian** [comment]
没必要那么激动嘛，也别先急着close。
-------
只是描述下服务器安装serverspeeder后流量吃的超级快，邮件通知我的VPS疑似入侵，看看大家有没有类似情况交流下。
