### ISSUE TITLE
install.sh: 第 40 行:[: 参数太多

### ISSUE THREAD

**Issue by CairoLee** [91yun/serverspeeder#49]
安装脚本在安装的过程中，出现了一个这样的提示：第 40 行:[: 参数太多 
不知道是不是安装脚本有问题，请排查。

```======================================
开始下载bin运行文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1280k  100 1280k    0     0   645k      0  0:00:01  0:00:01 --:--:--  645k
install.sh: 第 40 行:[: 参数太多
Installation done!
```

**Comment by CairoLee** [comment]
操作系统是 Centos 7.2，内核信息为：
Linux iZ6webj26vx9teij556zc0Z 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 91yun** [comment]
[重新精简了下锐速的安装shell文件，欢迎测试反馈。。。](https://bbs.91yun.org/discussion/30/%E9%87%8D%E6%96%B0%E7%B2%BE%E7%AE%80%E4%BA%86%E4%B8%8B%E9%94%90%E9%80%9F%E7%9A%84%E5%AE%89%E8%A3%85shell%E6%96%87%E4%BB%B6-%E6%AC%A2%E8%BF%8E%E6%B5%8B%E8%AF%95%E5%8F%8D%E9%A6%88#latest)

用论坛的这个来

**Comment by CairoLee** [comment]
@91yun 感谢您的快速回复，我刚注册，能审批一下么？账号是 cairolee

**Comment by CairoLee** [comment]
问题已经解决，新的脚本很精简，很给力
