### ISSUE TITLE
关机自动启动

### ISSUE THREAD

**Issue by panlivictory** [91yun/serverspeeder#51]
安装好后，请问重启CENTOS，速税会自动启动吗？在哪里可以修改呢

**Comment by 91yun** [comment]
把启动代码加入/etc/rc.local，如果是centos7，把启动代码加入/etc/rc.d/rc.local.

**Comment by DukeAnn** [comment]
bash serverspeeder.sh 这个代码？

**Comment by 91yun** [comment]
/serverspeeder/bin/serverSpeed.sh start
