### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ttc0419** [91yun/serverspeeder#53]
Installation done!

/etc/centos-release:CentOS Linux release 7.3.1611 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/redhat-release:CentOS Linux release 7.3.1611 (Core)
/etc/system-release:CentOS Linux release 7.3.1611 (Core)
(license B86A1F4C2D5BC477a0963e39)
...Failed to write configuration: /proc/net/appex/conservMode
[Running Status]
ServerSpeeder is NOT running!
version              3.10.61.12

**Comment by 91yun** [comment]
```...Failed to write configuration: /proc/net/appex/conservMode```
这种错误一般重启后重装能解决
