### ISSUE TITLE
锐速和iptables冲突吗？

### ISSUE THREAD

**Issue by lincchenl** [91yun/serverspeeder#57]
很感谢你的脚本，很好用，现在我有一个疑问。
我的vps现在开了80，81端口来扶墙，还有一个ssh端口。我把input chain里的除了这三个端口全部屏蔽，结果发现无法wget任何东西，然而ping是没有问题的。请问是因为锐速和iptables冲突还是说锐速要用到特殊的端口？谢了！

**Comment by ttc0419** [comment]
iptables -I INPUT -m state --state ESTABLISH,RELATED -j ACCEPT 允许连接外网

**Comment by 91yun** [comment]
锐速和iptables没任何关系
