### ISSUE TITLE
之前可以安装，现在安装出现错误，missing

### ISSUE THREAD

**Issue by louisyoung** [91yun/serverspeeder#59]

**Comment by 91yun** [comment]
什么错误？

**Comment by louisyoung** [comment]
缺失文件，应该是你的网站无法访问下载这两个文件。
​

2017-06-02 13:07 GMT+08:00 91yun <notifications@github.com>:

**Comment by louisyoung** [comment]
Installation done!

ERROR(CONFIGFILE): missing file: /serverspeeder/bin/acce-3.10.61.0-[CentOS_6.9_2.6.32-696.1.1.el6.x86_64]
chattr: No such file or directory while trying to stat /serverspeeder/etc/apx*
ERROR(CONFIGFILE): missing file: /serverspeeder/bin/acce-3.10.61.0-[CentOS_6.9_2.6.32-696.1.1.el6.x86_64]

**Comment by 91yun** [comment]
696的内核本来就不再支持之列,你是怎么安装的?一键代码肯定过不了检测啊.

**Comment by louisyoung** [comment]
Installation done!

ERROR(CONFIGFILE): missing file:
/serverspeeder/bin/acce-3.10.61.0-[CentOS_6.8_2.6.32-642.13.1.el6.x86_64]
chattr: No such file or directory while trying to stat
/serverspeeder/etc/apx*
ERROR(CONFIGFILE): missing file:
/serverspeeder/bin/acce-3.10.61.0-[CentOS_6.8_2.6.32-642.13.1.el6.x86_64]
[root@150-95-140-238 ~]# uname  -r
2.6.32-642.13.1.el6.x86_64


2017-06-02 17:38 GMT+08:00 91yun <notifications@github.com>:

**Comment by louisyoung** [comment]
centos 7一键安装也不行 算了 可能是我的原因吧 麻烦了

2017-06-02 18:07 GMT+08:00 Louis Young <louisyoung.cn@gmail.com>:

**Comment by 91yun** [comment]
你要再往上看是否wget成功了，也可能是你服务商屏蔽了域名ip之类的。

**Comment by pantouyu** [comment]
貌似也这样，使用旧版脚本出现这个问题，但是新版本却没有提示这个

ERROR(CONFIGFILE): missing file: /serverspeeder/bin/acce-3.10.61.0-[Debian_8_3.16.0-4-amd64]
chattr: No such file or directory while trying to stat /serverspeeder/etc/apx*
ERROR(CONFIGFILE): missing file: /serverspeeder/bin/acce-3.10.61.0-[Debian_8_3.16.0-4-amd64]

**Comment by 91yun** [comment]
把整个安装屏幕上的信息显示的都贴下

**Comment by pantouyu** [comment]
serverspeeder-all.sh                    100%[=================================================================================>]   9.82K  --.-KB/s   in 0s     

2017-06-05 09:00:33 (55.7 MB/s) - ‘serverspeeder-all.sh’ saved [10054/10054]

Ign http://mirrors.online.net jessie InRelease
Hit http://mirrors.online.net jessie Release.gpg                               
Hit http://mirrors.online.net jessie Release                                   
Hit http://www.deb-multimedia.org jessie InRelease                                                   
Hit http://mirrors.online.net jessie/main Sources                                                    
Hit http://mirrors.online.net jessie/non-free Sources                             
Hit http://www.deb-multimedia.org jessie/main amd64 Packages                                 
Hit http://mirrors.online.net jessie/contrib Sources                                         
Hit http://www.deb-multimedia.org jessie/main Translation-en                                                       
Hit http://mirrors.online.net jessie/main amd64 Packages                                                           
Hit http://mirrors.online.net jessie/non-free amd64 Packages                                 
Hit http://mirrors.online.net jessie/contrib amd64 Packages                
Hit http://mirrors.online.net jessie/contrib Translation-en                
Hit http://mirrors.online.net jessie/main Translation-en                   
Hit http://mirrors.online.net jessie/non-free Translation-en               
Hit http://security.debian.org jessie/updates InRelease                                                                                                        
Hit http://security.debian.org jessie/updates/main Sources                                                                                                     
Hit http://security.debian.org jessie/updates/contrib Sources                                                                                                  
Hit http://security.debian.org jessie/updates/non-free Sources                                                                                                 
Hit http://security.debian.org jessie/updates/main amd64 Packages                                                                                              
Hit http://security.debian.org jessie/updates/contrib amd64 Packages                                                                                           
Hit http://security.debian.org jessie/updates/non-free amd64 Packages                                                                                          
Hit http://security.debian.org jessie/updates/contrib Translation-en                                                                                           
Hit http://security.debian.org jessie/updates/main Translation-en                                                                                              
Hit http://security.debian.org jessie/updates/non-free Translation-en                                                                                          
Reading package lists... Done                                                                                                                                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version.
lsb-release is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
=================================================
操作系统：Debian 
发行版本：8 
内核版本：3.16.0-4-amd64 
位数：x64 
锐速版本：3.10.61.0 
=================================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
grep: serverspeederbin.txt: No such file or directory
grep: serverspeederbin.txt: No such file or directory
cat: serverspeederbin.txt: No such file or directory
http://soft.91yun.org/soft/serverspeeder/bin/Debian/8/3.16.0-4-amd64/x64/3.10.61.0/
MAC=2c:76:8a:ad:ce:38
======================================
开始下载安装包。。。。
======================================
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2017-06-05 09:00:45--  http://soft.91yun.org/soft/serverspeeder/91yunserverspeeder.tar.gz
Resolving soft.91yun.org (soft.91yun.org)... 104.27.171.19, 104.27.170.19
Connecting to soft.91yun.org (soft.91yun.org)|104.27.171.19|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://soft.91yun.org/soft/serverspeeder/91yunserverspeeder.tar.gz [following]
--2017-06-05 09:00:45--  https://soft.91yun.org/soft/serverspeeder/91yunserverspeeder.tar.gz
Connecting to soft.91yun.org (soft.91yun.org)|104.27.171.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 63693 (62K) [application/octet-stream]
Saving to: ‘91yunserverspeeder.tar.gz’

91yunserverspeeder.tar.gz               100%[=================================================================================>]  62.20K  --.-KB/s   in 0.005s 

2017-06-05 09:00:45 (11.2 MB/s) - ‘91yunserverspeeder.tar.gz’ saved [63693/63693]

91yunserverspeeder/
91yunserverspeeder/apxfiles/
91yunserverspeeder/apxfiles/bin/
91yunserverspeeder/apxfiles/bin/serverSpeeder.sh
91yunserverspeeder/apxfiles/bin/ethtool
91yunserverspeeder/apxfiles/bin/showConfig.sh
91yunserverspeeder/apxfiles/bin/utils.sh
91yunserverspeeder/apxfiles/bin/setConfig.sh
91yunserverspeeder/apxfiles/bin/update.sh
91yunserverspeeder/apxfiles/bin/renewLic.sh
91yunserverspeeder/apxfiles/etc/
91yunserverspeeder/apxfiles/etc/config
91yunserverspeeder/install.sh
======================================
开始下载授权文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
======================================
开始修改配置文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
序列号：
======================================
开始下载bin运行文件。。。。
======================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
cp: cannot remove ‘/serverspeeder/etc/apx.lic’: Operation not permitted
Installation done!

ERROR(CONFIGFILE): missing file: /serverspeeder/bin/acce-3.10.61.0-[Debian_8_3.16.0-4-amd64]
ERROR(CONFIGFILE): missing file: /serverspeeder/bin/acce-3.10.61.0-[Debian_8_3.16.0-4-amd64]

**Comment by 91yun** [comment]
你用错安装文件了，用最新的那个，不带-all的。GitHub说明里面最新的代码
