### ISSUE TITLE
我使用的系统是Centos6.7，总是间歇性断网！

### ISSUE THREAD

**Issue by predoyao** [91yun/serverspeeder#6]
用着用着网络就会断，然后ping我的服务器也ping不通了，过一会又能连通了，这是为什么呢？请问如何解决呢？？谢谢！！！

**Comment by 91yun** [comment]
应该不是锐速问题把。你把锐速停了看看。或者是大流量vps提供商封杀了？

**Comment by predoyao** [comment]
谢谢您的回答，我已经检测过多次了，我用 的是DO的vps，现在主机在San Francisco机房，我之前一直用finalspeed加速一直看youtube1080p从来都没有断过，用了锐速加速后，也是可以看1080p，但是就是时间久了就会停一次网，所以我感觉并不是提供商封杀的问题。。。感觉是主机网卡堵了？？？几分钟后就恢复。。。所以我真的不知道为啥，我使用的是centos，换了好几个机房什么加拿大，英国，美国的，都是会有断网的现象。。。。难道是我需要优化一下我的主机吗？

**Comment by 91yun** [comment]
运营商干扰

**Comment by fishg** [comment]
do就是间歇性断，用不用锐速一样

**Comment by cuigl** [comment]
碰到同样的问题，多个机器测试，怀疑是maxmode问题
