### ISSUE TITLE
装了锐速以后服务器被暴力破解 //误解了，不是锐速的事

### ISSUE THREAD

**Issue by redapple0204** [91yun/serverspeeder#65]
两台服务器，都装了锐速破解版
然后两台服务器自装上以来就一直被暴力破解，而且其中219.133.173.105这个ip甚至暴力破解成功了我的两台vps。
所以这到底是什么原因？

**Comment by neteroster** [comment]
补充：在服务器**被**暴力破解的同时，服务器可能也在破解别人。

在GCP计算引擎上出现了2小时CPU占用超过60%，DO上连续多天出现CPU占满

目前怀疑是锐速操作，正在查证
