### ISSUE TITLE
我的vps还是断网。。求帮忙分析

### ISSUE THREAD

**Issue by predoyao** [91yun/serverspeeder#7]
我用 的是DO的vps，现在主机在San Francisco机房，我之前一直用finalspeed加速一直看youtube1080p从来都没有断过，用了锐速加速后，也是可以看1080p，但是就是时间久了就会停一次网，所以我感觉并不是提供商封杀的问题。。。感觉是主机网卡堵了？？？几分钟后就恢复。。。所以我真的不知道为啥，我使用的是centos，换了好几个机房什么加拿大，英国，美国的，都是会有断网的现象。。。。难道是我需要优化一下我的主机吗？只要用锐速就会这样，不用锐速从来也没有断过。。。。
请求帮助

**Comment by 91yun** [comment]
可以加我qq13106510帮你看看

**Comment by 91yun** [comment]
运营商干扰，建议用ssr
