### ISSUE TITLE
这个破解版是不是真的没有任何限制？

### ISSUE THREAD

**Issue by reaCodes** [91yun/serverspeeder#8]
锐速有很多版本，免费版是20M加速，收费的有50M，100M等等加速的版本，这个破解版属于哪一种，或者还是没有速度限制？

**Comment by 91yun** [comment]
不限速

**Comment by reaCodes** [comment]
@91yun 我怎么感觉用了之后不太稳定，没有我另外一个当时用了免费版的锐速来的稳定，为什么

**Comment by 91yun** [comment]
破解只是破解授权文件，锐速版本和运行的bin文件的版本匹配都不知道有没一些特殊的设置，这个只有锐速自己知道了。一般不稳定都是内核版本不是非常匹配用了模糊匹配选择的。我自己用的几个完全匹配的内核和锐速版本，至今没啥问题。

**Comment by reaCodes** [comment]
@91yun 能不能推荐一下完全匹配的方案？我现在用的是Ubuntu 14.04.4 x64 ，内核是Ubuntu 14.04 x64 vmlinuz-3.13.0-32-generic

话说什么叫完全匹配的版本？

**Comment by 91yun** [comment]
ubuntu我不熟，我一直用centos。。。完全匹配就是完全按照http://www.91yun.org/wp-content/plugins/91yun-serverspeeder/systemlist.html这个对应关系。你可以在http://www.91yun.org/serverspeeder91yun这个地方找，因为拿到的对应包，未必能完全匹配上。
