### ISSUE TITLE
ubuntu14.04启动锐速报错

### ISSUE THREAD

**Issue by asuna** [91yun/serverspeeder#9]
启动锐速报错，Ubuntu_14.04_3.13.0-74-generic
以及...遇到了和另一个issue一样的版本匹配错误

``` bash
/serverspeeder/bin/acce-3.10.61.0-[Ubuntu_14.04_3.13.0-74-generic]: error while loading shared libraries: libssl.so.10: cannot open shared object
```

**Comment by asuna** [comment]
上面的问题已经自行解决，但是遇到了个新问题QAQ
ubuntu下更改网卡名称为eth0后，开启锐速，一直提示：
appex set wanif eth0 in routed mode

``` bash
Apr 26 02:00:22 sd-53285 kernel: [  238.509907] appex0: module license 'AppEx' taints kernel.
Apr 26 02:00:22 sd-53285 kernel: [  238.509911] Disabling lock debugging due to kernel taint
Apr 26 02:00:22 sd-53285 kernel: [  238.510807] AppEx Engine (Build Time: Jan 18 2016 - 13:40:21)
Apr 26 02:00:26 sd-53285 kernel: [  242.849389] appex: set wanIf eth0
Apr 26 02:00:26 sd-53285 kernel: [  242.849631] appex: set wanIf eth0 in routed mode
Apr 26 02:00:26 sd-53285 kernel: [  243.127925] appex: set wanIf eth0
Apr 26 02:00:26 sd-53285 kernel: [  243.128142] appex: set wanIf eth0 in routed mode
Apr 26 02:00:27 sd-53285 kernel: [  243.407746] appex: set wanIf eth0
Apr 26 02:00:27 sd-53285 kernel: [  243.407944] appex: set wanIf eth0 in routed mode
Apr 26 02:00:27 sd-53285 kernel: [  243.686701] appex: set wanIf eth0
Apr 26 02:00:27 sd-53285 kernel: [  243.686978] appex: set wanIf eth0 in routed mode
Apr 26 02:00:34 sd-53285 kernel: [  250.674297] AppEx Engine terminated
Apr 26 02:02:04 sd-53285 kernel: [  340.910447] AppEx Engine (Build Time: Jan 18 2016 - 13:40:21)
Apr 26 02:02:09 sd-53285 kernel: [  345.251773] appex: set wanIf eth0
Apr 26 02:02:09 sd-53285 kernel: [  345.260985] appex: set wanIf eth0 in routed mode
Apr 26 02:02:09 sd-53285 kernel: [  345.547240] appex: set wanIf eth0
Apr 26 02:02:09 sd-53285 kernel: [  345.553593] appex: set wanIf eth0 in routed mode
Apr 26 02:02:09 sd-53285 kernel: [  345.839511] appex: set wanIf eth0
Apr 26 02:02:09 sd-53285 kernel: [  345.845817] appex: set wanIf eth0 in routed mode
Apr 26 02:02:10 sd-53285 kernel: [  346.134416] appex: set wanIf eth0
Apr 26 02:02:10 sd-53285 kernel: [  346.140356] appex: set wanIf eth0 in routed mode
Apr 26 02:02:17 sd-53285 kernel: [  353.369785] AppEx Engine terminated
```

并且没过多久系统就挂了

**Comment by Rongdong53** [comment]
你好，请问你是怎么解决上一个问题的，我也遇到这样的问题

**Comment by asuna** [comment]
@Rongdong53 自己编译openssl, 更改网卡名字为eth0 (我原本的是em1

**Comment by Rongdong53** [comment]
openssl是什么？能具体指导下吗 我的QQ1596738684

**Comment by mengbingrock** [comment]
@Rongdong53  @asuna   遇到了和你们一样的问题，后来我把内核换成_24，避免了问题自动匹配正确成功安装。

**Comment by asuna** [comment]
@mengbingrock 正好月末打算reinstall下，到时候试试，thx~

**Comment by tangyl2000** [comment]
我vps系统是ubuntu 14.04，内核版本是：3.13.0-86-generic。手动下载的3.13.0-74-generic版本锐速，但安装过程中提示libcrypto.so.10找不到，貌似也是openss里的。
我手动编译了openssl 1.0.0t版本(ftp://ftp.openssl.org/source/openssl-1.0.0t.tar.gz)，但依然提示上面的错误。
不知道您用的哪个openssl版本，抽空请告知一下呗，谢谢。

**Comment by mengbingrock** [comment]
@tangyl2000    openssl 版本信息如下，希望能够帮到您。
`OpenSSL 1.0.1f 6 Jan 2014
built on: Mon May  2 16:53:18 UTC 2016
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"`

**Comment by tangyl2000** [comment]
谢谢楼上，我已经通过把内核手动升级到锐速能安装列表中的版本之一了，目前已成功安装，非常感谢您的指导～～～～

**Comment by ruiruige** [comment]
@91yun 这个问题现在搞定了吗？
我没法改内核的  ubuntu14.04.4   3.13.073  

![image](https://cloud.githubusercontent.com/assets/8370100/19295513/905acdf8-9067-11e6-8d3f-4e1007bf1f3e.png)

后来就是这个错误死活弄不好
